# -*- coding: utf-8 -*-
"""loss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7o8duMhzkcMjdEMn2LeaOZ6amPLp1_X
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

def triple_loss(s_logits, t_logits, s_hidden, t_hidden, mlm_labels, alpha=1.0, beta=1.0, gamma=1.0, temperature=2.0):
    s_log_probs = F.log_softmax(s_logits / temperature, dim=-1)
    t_probs = F.softmax(t_logits / temperature, dim=-1)
    loss_ce = F.kl_div(s_log_probs, t_probs, reduction="batchmean") * (temperature ** 2)

    loss_mlm = F.cross_entropy(s_logits.reshape(-1, s_logits.size(-1)), mlm_labels.reshape(-1), ignore_index=-100)

    loss_cos = 1 - F.cosine_similarity(s_hidden, t_hidden, dim=2).mean()

    total_loss = alpha * loss_ce + beta * loss_mlm + gamma * loss_cos
    return total_loss, loss_ce, loss_mlm, loss_cos